# Generated by Django 5.1.6 on 2025-02-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_word', models.CharField(max_length=10)),
                ('identified_word', models.CharField(max_length=10)),
                ('wrong_guesses', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField()),
                ('remaining_attempts', models.IntegerField()),
                ('game_status', models.CharField(default='InProgress', max_length=10)),
            ],
        ),
    ]
